# Generated by Django 4.2.27 on 2026-02-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0005_partymember_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='mic_required',
            field=models.BooleanField(default=False, verbose_name='마이크 필수'),
        ),
    ]
