# Generated by Django 4.2.27 on 2026-02-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0006_party_mic_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='mode',
            field=models.CharField(default='일반', max_length=20, verbose_name='게임 모드'),
        ),
    ]
