# Generated by Django 4.2.27 on 2026-02-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0007_alter_party_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='title',
            new_name='partyName',
        ),
        migrations.AlterField(
            model_name='party',
            name='mode',
            field=models.CharField(max_length=20, verbose_name='게임 모드'),
        ),
    ]
