# Generated by Django 4.2.27 on 2026-02-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0008_rename_title_party_partyname_alter_party_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='partyName',
        ),
        migrations.AlterField(
            model_name='party',
            name='current_member_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='party',
            name='mode',
            field=models.CharField(help_text='게임 모드 예: 랭크, 일반, 칼바람, 신속, 내전', max_length=50),
        ),
    ]
