# Generated by Django 4.2.27 on 2026-02-22 14:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_birth_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='전화번호는 숫자 11자리여야 합니다.', regex='^\\d{11}$')]),
        ),
    ]
